# Generated by Django 6.0 on 2025-12-17 07:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_back',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_viezd',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
